### PR TITLE
Range UGen: map signal inputs from one range to another

### PR DESCRIPTION
**Pull request by nshaheed**
This is a chugin that takes an input signal and scales it to a different range as its output, i.e. taking a sin osc and mapping the range from (-1,1) to (0, 1). This is useful both for making LFOs as well as dealing with ugens that are signal-rate but not intended for audio output (such as manipulating latent dimensions in VAEs or GANs)

```
// Use scaler to make an easy vibrato
SinOsc lfo => Range r => blackhole;
SinOsc tone => dac;

// Help reveals all secrets
Range.help();

3 => lfo.freq;
// Modulate frequency +- 10Hz around A440
(0, 1, 440, 10) => r.radius;

// This is equivalent to the above line, but sets the input/output range specifically
// (-1, 1, 430, 450) => r.range 

while(10::ms => now) {
	r.last() => tone.freq;
}

```

### CODE REVIEW

**Comment by DBraun** [comment]
Nice! This seems worthy of being a built-in UGen, not a chugin. If you have TouchDesigner installed, I would recommend copying a few more ideas from the Math CHOP. Then, for yet another UGen, you could take some ideas from the Limit CHOP.

**Comment by DBraun** [comment]
Also, if it's a UGen, then you can use the .op property: https://archive.flossmanuals.net/chuck/ch033_unit-generators.html This would correspond to how the Math CHOP can Combine Channel OPs.

**Comment by DBraun** [comment]
Also, maybe use the name `Scale` to match Max/MSP, or `Remap`. `Math` is already taken...

**Comment by nshaheed** [comment]
The math and limit chops definitely look cool! imo having a simpler, self-contained, arithmetic UGens would be a cleaner and more flexible way to handle this than the totalist approach that TD is taking here. Maybe the included limiter is out of scope of Scaler and should be moved into its own UGen. Perhaps future work could be to have a bunch of different single-purpose ugens under the Math namespace (i.e. Math.Scaler & Math.Inverse).

re the name: I'm specifically trying to avoid `Scale` both because it's a loaded term in musical context, and because it conflicts with the [lick Scale object](https://github.com/heuermh/lick/blob/e2349b45ac2c557c0193a8366cfaec39922f6d4b/lick/interval/Scale.ck#L23). Maybe Range is a better name?

**Comment by DBraun** [comment]
Sure that's fair. I would also want the last two args to represent the output low and output high. The idea of an output center and a radius is nice, but I would also want the more typical way like Max/MSP/Processing/TouchDesigner.

Processing (`map`): https://p5js.org/reference/#/p5/map

**Comment by nshaheed** [comment]
It can do both! You just use Scaler.range instead of Scaler.radius. I updated the documentation and added a README so that's more clear.

**Comment by nshaheed** [comment]
I've renamed the ugen to Range

**Comment by gewang** [comment]
thank you @nshaheed

**Pull request merged**
