### PR TITLE
Add separate driveDb for drive in decibels (dB).

### LINKED ISSUE #39: ABSaturator | getDrive() returns linear value while setDrive() wants values in dB
At row 121 we have:
`float setDrive(float d)
    {
        m_drive = dB2lin(d);
        return m_drive;
    }
    
    float getDrive() { return m_drive; }`

I think the 2 should use the same value
I had a the following scenario:
`ABSaturator saturator[2];
35 => saturator[0].drive => saturator[1].drive;`

and it took me 20 mins to figure out why they sounded different and where spitting out what it seemed were random values :)

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #39 
Replaces https://github.com/jwmatthys/chugins/pull/7

### CODE REVIEW

**Comment by heuermh** [comment]
Ping @gewang @spencersalazar @lathertonj for review

**Comment by heuermh** [comment]
Ping @nshaheed for review

**Review by spencersalazar — CHANGES_REQUESTED** [review]
This will break any existing programs using ABSaturator.setDrive (and quite loudly so as db gain would be re-interpreted as linear). Im not sure why not just return db(m_drive) in ABSaturator.getDrive?

**Comment by heuermh** [comment]
> Im not sure why not just return db(m_drive) in ABSaturator.getDrive?

Good question, I don't remember the original motivation 😁

**Pull request closed without merging**
